spring:
  output:
    ansi:
      enabled: always

pagehelper:
  helper-dialect: mysql
  reasonable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brothers-of-study
    username: bos
    password: bos

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    mapper-locations: classpath:/mapper/**/*.xml
